# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: healthz.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'healthz.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhealthz.proto\x12\x07healthz\"\x10\n\x0eHealthzRequest\"!\n\x0fHealthzResponse\x12\x0e\n\x06status\x18\x01 \x01(\r2F\n\x06Status\x12<\n\x07Healthz\x12\x17.healthz.HealthzRequest\x1a\x18.healthz.HealthzResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'healthz_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHZREQUEST']._serialized_start=26
  _globals['_HEALTHZREQUEST']._serialized_end=42
  _globals['_HEALTHZRESPONSE']._serialized_start=44
  _globals['_HEALTHZRESPONSE']._serialized_end=77
  _globals['_STATUS']._serialized_start=79
  _globals['_STATUS']._serialized_end=149
# @@protoc_insertion_point(module_scope)
